# Generated by Django 4.1.7 on 2023-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producermodel",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producermodel",
            name="default_title",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="producermodel",
            name="established",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="producermodel",
            name="japanese_title",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="producermodel",
            name="name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
