# Generated by Django 4.1.7 on 2023-03-03 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0002_producermodel_about_producermodel_default_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producermodel",
            name="type",
        ),
    ]
