# Generated by Django 4.2 on 2023-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0003_remove_producermodel_default_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producermodel",
            old_name="japanese_title",
            new_name="name_japanese",
        ),
    ]
