# Generated by Django 4.1.7 on 2023-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0003_remove_producermodel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="producermodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="producermodel",
            name="mal_id",
            field=models.IntegerField(unique=True),
        ),
    ]
