# Generated by Django 4.1.7 on 2023-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0004_producermodel_kitsu_id_alter_producermodel_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producermodel",
            name="mal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
