# Generated by Django 4.2.2 on 2023-06-17 14:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0014_alter_animegenremodel_is_locked_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="animemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "name_japanese"], name="anime_anime_name_301f1e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="animenamesynonymmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="anime_anime_name_81fa03_gin"
            ),
        ),
    ]
