# Generated by Django 4.1.1 on 2022-09-06 10:43

from django.db import migrations, models

import apps.staffs.models
import core.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffAlternateNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StaffModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, null=True, unique=True)),
                (
                    "kitsu_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                (
                    "anilist_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=1024)),
                ("given_name", models.CharField(max_length=1024, null=True)),
                ("family_name", models.CharField(max_length=1024, null=True)),
                (
                    "staff_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=core.storages.OverwriteStorage,
                        upload_to=apps.staffs.models.FileField.staff,
                    ),
                ),
                ("about", models.TextField(null=True)),
                (
                    "alternate_names",
                    models.ManyToManyField(to="staffs.staffalternatenamemodel"),
                ),
            ],
            options={
                "verbose_name": "Staff | People",
                "verbose_name_plural": "Staffs | Peoples",
            },
        ),
    ]
