"""Create Auto Increment

Revision ID: 19f71c3b829c
Revises: 
Create Date: 2024-07-29 16:56:04.069357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f71c3b829c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mal_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_kanji', sa.String(), nullable=True),
    sa.Column('character_image', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('lol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id', 'name', 'name_kanji', name='_name_uc')
    )
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_index(op.f('ix_character_mal_id'), 'character', ['mal_id'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_mal_id'), table_name='character')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
