# Generated by Django 4.1.1 on 2022-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="anilist_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="family_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="given_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="mal_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
