# Generated by Django 4.1.7 on 2023-03-03 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffalternatenamemodel",
            options={
                "verbose_name": "Staff | People ( Alternate Name )",
                "verbose_name_plural": "Staffs | People ( Alternate Names )",
            },
        ),
    ]
