# Generated by Django 4.1.2 on 2022-10-29 02:59

import core.storages
import dynamic_filenames

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_alter_staffmodel_about_alter_staffmodel_anilist_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="staff_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage,
                upload_to=dynamic_filenames.FilePattern(filename_pattern="/staff{ext}"),
            ),
        ),
    ]
