# Generated by Django 4.1.5 on 2023-01-13 03:42

import core.storages
from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0003_alter_staffmodel_staff_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="staff_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="staffs/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
