# Generated by Django 4.2 on 2023-04-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("staffs", "0003_staffmodel_created_at_staffmodel_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="staff_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.image"
            ),
        ),
    ]
