# Generated by Django 4.1.5 on 2023-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0004_alter_staffmodel_staff_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="anilist_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="mal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
