# Generated by Django 4.2 on 2023-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0004_staffmodel_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
