# Generated by Django 4.1.5 on 2023-01-14 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0005_alter_staffmodel_anilist_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffalternatenamemodel",
            options={
                "verbose_name": "Staff Alternate Name",
                "verbose_name_plural": "Staff Alternate Names",
            },
        ),
    ]
