# Generated by Django 5.0b1 on 2023-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0007_alter_staffmodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="is_locked",
            field=models.BooleanField(db_default=models.Value(False)),
        ),
    ]
