# Generated by Django 4.0.2 on 2022-02-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default=None, upload_to="avatars"),
        ),
    ]
