# Generated by Django 4.0.2 on 2022-02-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="avatars"
            ),
        ),
    ]
