# Generated by Django 4.1 on 2022-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PeopleAlternateNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PeopleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "kitsu_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                (
                    "anilist_id",
                    models.IntegerField(db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(db_index=True, max_length=1024)),
                ("given_name", models.CharField(db_index=True, max_length=1024)),
                ("family_name", models.CharField(db_index=True, max_length=1024)),
                ("about", models.TextField()),
            ],
            options={
                "verbose_name": "Anime People",
            },
        ),
    ]
