# Generated by Django 4.1 on 2022-08-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peoplemodel",
            options={"verbose_name": "People", "verbose_name_plural": "Peoples"},
        ),
    ]
