# Generated by Django 4.0.2 on 2022-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeModel",
            fields=[
                ("episode_number", models.AutoField(primary_key=True, serialize=False)),
                ("episode_name", models.CharField(max_length=1024)),
                (
                    "episode_cover",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="episode_cover"
                    ),
                ),
                (
                    "episode_file",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="episode"
                    ),
                ),
            ],
        ),
    ]
