# Generated by Django 4.0.2 on 2022-02-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_alter_episodemodel_episode_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodemodel",
            name="anime_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.animenamemodel",
            ),
            preserve_default=False,
        ),
    ]
