# Generated by Django 4.1.5 on 2023-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studiomodel",
            name="mal_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="studiomodel",
            name="name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="studiomodel",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
