# Generated by Django 4.0.2 on 2022-02-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anime_name", models.CharField(max_length=1024)),
                (
                    "anime_cover",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="anime"
                    ),
                ),
            ],
        ),
    ]
