# Generated by Django 4.0.3 on 2022-03-11 05:58

from django.db import migrations, models
import apps.upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_rename_animenamemodel_animeinfomodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episodemodel",
            old_name="anime_name",
            new_name="anime",
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.upload.models.FileField.episode_cover,
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.upload.models.FileField.episode_upload,
            ),
        ),
    ]
