# Generated by Django 4.0.3 on 2022-03-11 06:03

from django.db import migrations, models
import apps.upload.models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0007_rename_anime_name_episodemodel_anime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.upload.models.FileField.anime_cover,
            ),
        ),
    ]
