# Generated by Django 4.0.3 on 2022-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0008_alter_animeinfomodel_anime_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodemodel",
            name="episode_summary",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
