# Generated by Django 4.0.3 on 2022-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0009_episodemodel_episode_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="anime",
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="episodes",
            field=models.ManyToManyField(to="upload.episodemodel"),
        ),
    ]
