# Generated by Django 4.0.3 on 2022-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0011_episodecommentmodel_episodemodel_episode_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="episode_comment",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="episode_comment",
            field=models.ManyToManyField(null=True, to="upload.episodecommentmodel"),
        ),
    ]
