# Generated by Django 4.0.3 on 2022-03-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0012_remove_episodemodel_episode_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="episode_comment",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="episode_comments",
            field=models.ManyToManyField(
                blank=True, null=True, to="upload.episodecommentmodel"
            ),
        ),
    ]
