# Generated by Django 4.0.3 on 2022-03-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0015_episodemodel_episode_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_comments",
            field=models.ManyToManyField(blank=True, to="upload.episodecommentmodel"),
        ),
    ]
