# Generated by Django 4.0.3 on 2022-03-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0016_alter_episodemodel_episode_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
