# Generated by Django 4.0.3 on 2022-03-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0017_alter_episodemodel_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={"verbose_name": "Anime info"},
        ),
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={"verbose_name": "User comment"},
        ),
        migrations.AlterModelOptions(
            name="episodemodel",
            options={"verbose_name": "Episode info"},
        ),
    ]
