# Generated by Django 4.0.3 on 2022-03-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0018_alter_animeinfomodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodecommentmodel",
            name="comment_added",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
