# Generated by Django 4.0.3 on 2022-03-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0019_episodecommentmodel_comment_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={"ordering": ("-comment_added",), "verbose_name": "User comment"},
        ),
    ]
