# Generated by Django 4.0.3 on 2022-03-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0021_remove_episodemodel_episode_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodemodel",
            name="episode_comments",
            field=models.ManyToManyField(blank=True, to="upload.episodecommentmodel"),
        ),
    ]
