# Generated by Django 4.0.3 on 2022-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0024_alter_animeinfomodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeinfomodel",
            name="episodes",
            field=models.ManyToManyField(blank=True, to="upload.episodemodel"),
        ),
    ]
