# Generated by Django 4.0.3 on 2022-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0025_alter_animeinfomodel_episodes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={
                "ordering": ("-malid",),
                "verbose_name": "Anime info",
            },
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="malid",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
