# Generated by Django 4.0.3 on 2022-03-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0026_alter_animeinfomodel_options_animeinfomodel_malid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={
                "ordering": ("-mal_id",),
                "verbose_name": "Anime info",
            },
        ),
        migrations.RenameField(
            model_name="animeinfomodel",
            old_name="malid",
            new_name="mal_id",
        ),
    ]
