# Generated by Django 4.0.3 on 2022-03-21 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0027_alter_animeinfomodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
