# Generated by Django 4.0.3 on 2022-03-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0028_animeinfomodel_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="anime_cover",
        ),
    ]
