# Generated by Django 4.0.3 on 2022-03-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0029_remove_animeinfomodel_anime_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={"ordering": ("-mal_id",), "verbose_name": "Animes"},
        ),
    ]
