# Generated by Django 4.0.3 on 2022-03-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0030_alter_animeinfomodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={
                "ordering": ("-mal_id",),
                "verbose_name": "Anime",
            },
        ),
    ]
