# Generated by Django 4.0.3 on 2022-03-22 13:46

import apps.upload.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0031_alter_animeinfomodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_aired_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_aired_to",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.upload.models.FileField.anime_cover,
            ),
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_name_japanese",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_source",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
