# Generated by Django 4.0.3 on 2022-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0034_alter_animeinfomodel_anime_aired_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_name_japanese",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
