# Generated by Django 4.0.3 on 2022-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0036_alter_animeinfomodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_rating",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
