# Generated by Django 4.0.3 on 2022-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0038_alter_animeinfomodel_anime_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="episodes",
        ),
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="mal_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
