# Generated by Django 4.0.3 on 2022-03-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0040_animeinfomodel_episodes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodemodel",
            options={"ordering": ("id",), "verbose_name": "Episode"},
        ),
    ]
