# Generated by Django 4.0.3 on 2022-03-26 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("upload", "0041_alter_episodemodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={"ordering": ("-comment_added",), "verbose_name": "User Comment"},
        ),
        migrations.CreateModel(
            name="EpisodeTimeStampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User TimeStamp",
            },
        ),
    ]
