# Generated by Django 4.0.3 on 2022-03-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0043_episodemodel_episode_timestamps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodetimestampmodel",
            options={"verbose_name": "User Timestamp"},
        ),
    ]
