# Generated by Django 4.0.2 on 2022-02-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_episodemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_number",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
