# Generated by Django 4.0.2 on 2022-02-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_episodemodel_anime_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="anime_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.animenamemodel",
            ),
        ),
    ]
