# Generated by Django 4.0 on 2021-12-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(
                choices=[
                    ("https://seccdn.libravatar.org", "Libravatar"),
                    ("https://www.gravatar.com", "Gravatar"),
                ],
                default="https://seccdn.libravatar.org",
                max_length=50,
            ),
        ),
    ]
