# Generated by Django 4.0 on 2021-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language_choice",
            field=models.CharField(
                choices=[("Bangla", "bn"), ("English", "en"), ("Japanese", "jp")],
                default="English",
                max_length=20,
            ),
        ),
    ]
