# Generated by Django 4.0.2 on 2022-02-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customuser_language_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_url',
        ),
    ]
