# Generated by Django 4.1 on 2022-08-11 05:52

import apps.api.v1.characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeProducerModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Producer",
            },
        ),
        migrations.CreateModel(
            name="AnimeStudioModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(db_index=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Studio",
            },
        ),
        migrations.CreateModel(
            name="CharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=1024, unique=True)),
                (
                    "character_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.api.v1.characters.models.FileField.anime_charater,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anime Character",
            },
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_characters",
            field=models.ManyToManyField(blank=True, to="anime.charactermodel"),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_producers",
            field=models.ManyToManyField(blank=True, to="anime.animeproducermodel"),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_studios",
            field=models.ManyToManyField(blank=True, to="anime.animestudiomodel"),
        ),
    ]
