# Generated by Django 4.1 on 2022-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermodel",
            name="about",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="charactermodel",
            name="name_kanji",
            field=models.CharField(
                db_index=True, default="", max_length=1024, unique=True
            ),
            preserve_default=False,
        ),
    ]
