# Generated by Django 4.1 on 2022-08-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={"verbose_name": "Anime Info"},
        ),
    ]
