# Generated by Django 4.1 on 2022-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        ("anime", "0002_alter_animeinfomodel_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimeCharacterModel",
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_characters",
            field=models.ManyToManyField(
                blank=True, to="characters.animecharactermodel"
            ),
        ),
    ]
