# Generated by Django 4.1 on 2022-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_charactermodel_about_charactermodel_name_kanji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="name_kanji",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, null=True
            ),
        ),
    ]
