# Generated by Django 4.1 on 2022-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_alter_charactermodel_name_kanji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
