# Generated by Django 4.1 on 2022-08-07 06:01

import apps.api.v1.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_delete_animecharactermodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.api.v1.anime.models.FileField.anime_banner,
            ),
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.api.v1.anime.models.FileField.anime_cover,
            ),
        ),
    ]
