# Generated by Django 4.1 on 2022-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_rename_animeproducermodel_producermodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="producermodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producermodel",
            name="mal_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
