# Generated by Django 4.1 on 2022-08-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_rename_animecharactermodel_charactermodel"),
        ("anime", "0004_alter_animeinfomodel_anime_banner_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnimeInfoModel",
            new_name="AnimeModel",
        ),
        migrations.AlterModelOptions(
            name="animemodel",
            options={"verbose_name": "Anime"},
        ),
    ]
