# Generated by Django 4.1 on 2022-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_alter_charactermodel_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="name",
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
