# Generated by Django 4.1 on 2022-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_producermodel_id_alter_producermodel_mal_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(db_index=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Studio",
            },
        ),
        migrations.DeleteModel(
            name="AnimeStudioModel",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_studios",
            field=models.ManyToManyField(blank=True, to="anime.studiomodel"),
        ),
    ]
