# Generated by Django 4.1 on 2022-08-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_alter_charactermodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermodel",
            name="kitsu_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
