# Generated by Django 4.1 on 2022-08-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_rename_animeinfomodel_animemodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="anilist_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="kitsu_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="mal_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
