# Generated by Django 4.1 on 2022-08-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0001_initial"),
        ("anime", "0006_animemodel_anilist_id_animemodel_kitsu_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimeProducerModel",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_producers",
            field=models.ManyToManyField(blank=True, to="producers.animeproducermodel"),
        ),
    ]
