# Generated by Django 4.1 on 2022-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0006_charactermodel_kitsu_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermodel",
            name="anilist_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
