# Generated by Django 4.1 on 2022-08-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0001_initial"),
        ("anime", "0007_delete_animeproducermodel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimeStudioModel",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_studios",
            field=models.ManyToManyField(blank=True, to="studios.animestudiomodel"),
        ),
    ]
