# Generated by Django 4.2.4 on 2023-08-31 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0006_alter_episodecommentmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodetimestampmodel",
            name="episode",
        ),
    ]
