# Generated by Django 5.0rc1 on 2023-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("episodes", "0009_alter_episodecommentmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_comments",
            field=models.ManyToManyField(blank=True, to="comments.commentmodel"),
        ),
        migrations.DeleteModel(
            name="EpisodeCommentModel",
        ),
    ]
