# Generated by Django 4.1 on 2022-09-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffmodel",
            options={
                "verbose_name": "Staff | People",
                "verbose_name_plural": "Staffs | Peoples",
            },
        ),
        migrations.AddField(
            model_name="staffmodel",
            name="alternate_names",
            field=models.ManyToManyField(to="staff.staffalternatenamemodel"),
        ),
    ]
