# Generated by Django 4.1 on 2022-09-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staffmodel_options_staffmodel_alternate_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="about",
            field=models.TextField(null=True),
        ),
    ]
