# Generated by Django 4.1 on 2022-09-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_staffmodel_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="family_name",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="given_name",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
