# Generated by Django 4.1.1 on 2022-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_staffmodel_staff_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="mal_id",
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
