# Generated by Django 4.1.1 on 2022-09-05 13:21

import apps.staff.models
import core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_alter_staffmodel_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="staff_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage,
                upload_to=apps.staff.models.FileField.staff,
            ),
        ),
    ]
