<LoginScreen>
    name: "screen B"
    hero_to: hero_to
    md_bg_color: "cadetblue"

    MDHeroTo:
        id: hero_to
        tag: "hero"
        size_hint: None, None
        size: "220dp", "220dp"
        pos_hint: {"center_x": .5, "center_y": .5}

    MDRaisedButton:
        text: "Move Hero To Screen A"
        pos_hint: {"center_x": .5}
        y: "36dp"
        on_release:
            root.current_heroes = ["hero"]
            root.current = "screen A"