# Generated by Django 4.2 on 2023-04-13 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0004_episodemodel_created_at_episodemodel_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="comment_added",
        ),
        migrations.AddField(
            model_name="episodecommentmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="episodetimestampmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
