# Generated by Django 4.0.3 on 2022-03-26 12:15

import apps.anime.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeCommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("comment_added", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Comment",
                "ordering": ("-comment_added",),
            },
        ),
        migrations.CreateModel(
            name="EpisodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_name", models.CharField(max_length=1024)),
                (
                    "episode_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.anime.models.FileField.episode_cover,
                    ),
                ),
                (
                    "episode_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.anime.models.FileField.episode_upload,
                    ),
                ),
                (
                    "episode_summary",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("episode_number", models.BigIntegerField(default=0)),
                (
                    "episode_comments",
                    models.ManyToManyField(blank=True, to="anime.episodecommentmodel"),
                ),
            ],
            options={
                "verbose_name": "Episode",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AnimeInfoModel",
            fields=[
                ("anime_name", models.CharField(max_length=1024)),
                (
                    "mal_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("anime_aired_from", models.DateTimeField(blank=True, null=True)),
                ("anime_aired_to", models.DateTimeField(blank=True, null=True)),
                (
                    "anime_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.anime.models.FileField.anime_cover,
                    ),
                ),
                ("anime_name_japanese", models.CharField(max_length=1024, null=True)),
                (
                    "anime_source",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("anime_background", models.TextField(blank=True, null=True)),
                ("anime_synopsis", models.TextField(blank=True, null=True)),
                (
                    "anime_rating",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "episodes",
                    models.ManyToManyField(blank=True, to="anime.episodemodel"),
                ),
            ],
            options={
                "verbose_name": "Anime",
                "ordering": ("mal_id",),
            },
        ),
        migrations.CreateModel(
            name="EpisodeTimeStampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("episode_number", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "User Timestamp",
            },
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="episode_timestamps",
            field=models.ManyToManyField(blank=True, to="anime.episodetimestampmodel"),
        ),
    ]
