# Generated by Django 4.0.3 on 2022-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "anime",
            "0001_initial_squashed_0046_episodetimestampmodel_episode_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeGenres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="episodetimestampmodel",
            name="episode_number",
            field=models.IntegerField(),
        ),
    ]
