# Generated by Django 4.0.3 on 2022-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_animegenres_alter_animeinfomodel_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animegenres",
            options={"ordering": ("id",), "verbose_name": "Anime Genre"},
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenres"),
        ),
    ]
