# Generated by Django 4.0.3 on 2022-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_alter_animegenres_options_animeinfomodel_genres"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animegenres",
            options={"ordering": ("mal_id",), "verbose_name": "Anime Genre"},
        ),
        migrations.RenameField(
            model_name="animegenres",
            old_name="genre",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="animegenres",
            name="id",
        ),
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="genres",
        ),
        migrations.AddField(
            model_name="animegenres",
            name="mal_id",
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animegenres",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
