# Generated by Django 4.0.3 on 2022-03-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_alter_animegenres_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenres"),
        ),
    ]
