# Generated by Django 4.0.3 on 2022-04-03 14:13

import apps.anime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_animecharactermodel_animerecommendationmodel_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animecharactermodel",
            options={"ordering": ("mal_id",)},
        ),
        migrations.AlterModelOptions(
            name="animerecommendationmodel",
            options={"ordering": ("mal_id",)},
        ),
        migrations.AddField(
            model_name="animecharactermodel",
            name="character_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.anime.models.FileField.anime_charater,
            ),
        ),
        migrations.AddField(
            model_name="animecharactermodel",
            name="mal_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animecharactermodel",
            name="name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
