# Generated by Django 4.0.3 on 2022-03-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_animeinfomodel_genres"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnimeGenres",
            new_name="AnimeGenreModel",
        ),
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="genres",
        ),
    ]
