# Generated by Django 4.0.3 on 2022-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0006_rename_animegenres_animegenremodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenremodel"),
        ),
    ]
