# Generated by Django 4.0.3 on 2022-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0007_animeinfomodel_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="mal_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
