# Generated by Django 4.0.3 on 2022-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0008_alter_animegenremodel_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="mal_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
