# Generated by Django 4.0.3 on 2022-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0009_alter_animegenremodel_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
