# Generated by Django 4.0.3 on 2022-04-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_animerecommendationmodel_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeinfomodel',
            name='anime_recommendations',
        ),
    ]
