# Generated by Django 4.0.3 on 2022-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0011_alter_episodecommentmodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeProducerModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("type", models.CharField(default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Producer",
                "ordering": ("mal_id",),
            },
        ),
        migrations.CreateModel(
            name="AnimeThemeModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("type", models.CharField(default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Theme",
                "ordering": ("mal_id",),
            },
        ),
    ]
