# Generated by Django 4.0.3 on 2022-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_remove_animeinfomodel_anime_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animerecommendationmodel',
            name='entry',
        ),
        migrations.AddField(
            model_name='animerecommendationmodel',
            name='entry',
            field=models.ManyToManyField(blank=True, to='anime.animeinfomodel'),
        ),
    ]
