# Generated by Django 4.0.3 on 2022-03-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0013_animestudiomodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animeinfomodel",
            old_name="episodes",
            new_name="anime_episodes",
        ),
        migrations.RenameField(
            model_name="animeinfomodel",
            old_name="genres",
            new_name="anime_genres",
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_producers",
            field=models.ManyToManyField(blank=True, to="anime.animeproducermodel"),
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_studios",
            field=models.ManyToManyField(blank=True, to="anime.animestudiomodel"),
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_themes",
            field=models.ManyToManyField(blank=True, to="anime.animethememodel"),
        ),
    ]
