# Generated by Django 4.0.3 on 2022-03-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0015_animeinfomodel_id_alter_animeinfomodel_mal_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animeinfomodel",
            name="anime_genres",
        ),
    ]
