# Generated by Django 4.0.3 on 2022-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_remove_animerecommendationmodel_anime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerecommendationmodel',
            name='anime',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
