# Generated by Django 4.0.3 on 2022-03-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_remove_animeinfomodel_anime_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfomodel',
            name='anime_genres',
            field=models.ManyToManyField(blank=True, to='anime.animegenremodel'),
        ),
    ]
