# Generated by Django 4.0.3 on 2022-03-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0017_animeinfomodel_anime_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeinfomodel',
            name='anime_themes',
        ),
    ]
