# Generated by Django 4.0.3 on 2022-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0021_remove_animeinfomodel_anime_producers'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfomodel',
            name='anime_studios',
            field=models.ManyToManyField(blank=True, to='anime.animestudiomodel'),
        ),
    ]
