# Generated by Django 4.0.3 on 2022-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0023_animeinfomodel_anime_producers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeSynonymModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Anime Synonyms",
                "ordering": ("-id",),
            },
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_name_synonyms",
            field=models.ManyToManyField(blank=True, to="anime.animesynonymmodel"),
        ),
    ]
