# Generated by Django 4.0.3 on 2022-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0024_animesynonymmodel_animeinfomodel_anime_name_synonyms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animesynonymmodel",
            options={"ordering": ("-id",), "verbose_name": "Anime Synonym"},
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_name",
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_name_japanese",
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="animesynonymmodel",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
