# Generated by Django 5.0b1 on 2023-10-29 05:51

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0006_staffalternatenamemodel_staff_alternate_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
