# Generated by Django 4.1 on 2022-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                verbose_name="username",
            ),
        ),
    ]
