# Generated by Django 4.1a1 on 2022-06-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kitsumodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="malmodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="AnilistModel",
        ),
        migrations.DeleteModel(
            name="KitsuModel",
        ),
        migrations.DeleteModel(
            name="MalModel",
        ),
    ]
