# Generated by Django 4.1 on 2022-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip",
            field=models.GenericIPAddressField(default="0.0.0.0"),
            preserve_default=False,
        ),
    ]
