# Generated by Django 4.1 on 2022-08-07 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="username_discriminator",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(9999),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("username", "username_discriminator")},
        ),
    ]
