# Generated by Django 4.1 on 2022-08-07 17:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0003_alter_user_options_user_username_discriminator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username_discriminator",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        settings.USERNAME_DISCRIMINATOR_LENGTH
                    ),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
