# Generated by Django 4.1 on 2022-08-07 21:41

import django.core.validators
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0005_alter_user_username_discriminator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username_discriminator",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.RegexValidator(
                        code="nomatch",
                        message="Length has to be 4",
                        regex="^(?=[\S\s]{1,%d}$)[\S\s]*"
                        % settings.USERNAME_DISCRIMINATOR_LENGTH,
                    ),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
