# Generated by Django 4.1 on 2022-08-10 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username_discriminator",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="nomatch",
                        message="Length has to be 4",
                        regex="^(?=[\\S\\s]{1,4}$)[\\S\\s]*",
                    ),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
