# Generated by Django 4.1 on 2022-08-10 16:45

import apps.__user__.validators.username
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0011_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                validators=[apps.__user__.validators.username.username_validator],
                verbose_name="username",
            ),
        ),
    ]
