# Generated by Django 4.1 on 2022-08-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("__user__", "0012_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="video_volume",
        ),
    ]
