# Generated by Django 4.2 on 2023-04-13 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0007_animemodel_created_at_alter_animemodel_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animemodel",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
