# Generated by Django 4.2 on 2023-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0009_animegenremodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="is_locked",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
