# Generated by Django 4.2.2 on 2023-06-17 14:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0015_animemodel_anime_anime_name_301f1e_gin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="animemodel",
            name="anime_anime_name_301f1e_gin",
        ),
        migrations.RemoveIndex(
            model_name="animenamesynonymmodel",
            name="anime_anime_name_81fa03_gin",
        ),
        migrations.AddIndex(
            model_name="animemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "name_japanese"],
                name="anime_name|name_japanese_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="animenamesynonymmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="anime_name_synonym_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
