# Generated by Django 4.2.4 on 2023-08-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0016_remove_animemodel_anime_anime_name_301f1e_gin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="animemodel",
            name="anime_name|name_japanese_idx",
        ),
        migrations.RemoveIndex(
            model_name="animenamesynonymmodel",
            name="anime_name_synonym_idx",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="name",
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="name_japanese",
            field=models.CharField(blank=True, db_index=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="animenamesynonymmodel",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
