import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import localFont from "next/font/local";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const KokoroFont = localFont({
  src: [
    // Regular
    {
      path: "../fonts/Kokoro/Kokoro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Kokoro/Kokoro-SemiBold.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../fonts/Kokoro/Kokoro-Bold.woff2",
      weight: "700",
      style: "normal",
    },

    // Italic
    {
      path: "../fonts/Kokoro/Kokoro-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/Kokoro/Kokoro-SemiBoldItalic.woff2",
      weight: "500",
      style: "italic",
    },

    {
      path: "../fonts/Kokoro/Kokoro-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${KokoroFont.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
