# Generated by Django 4.1.7 on 2023-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodemodel",
            name="episode_type",
            field=models.CharField(
                blank=True, choices=[("sub", "sub"), ("dub", "dub")], max_length=3
            ),
        ),
    ]
