export type Anime = {
    mal_id: number;
    anilist_id: number | null;
    kitsu_id: number | null;
    name: string | null | "";
    name_japanese: string | "" | null;
    name_synonyms: string[];
    aired_from: null | string;
    aired_to: null | string;
    banner: null | string;
    cover: null | string;
    banner_background_color: null | string;
    cover_background_color: null | string;
    synopsis: string | "";
    background: string | "";
    source: string | null;
    rating: string | null | "";
    genres: Array<{ name: string }>;
    themes: string[];
    characters: string[];
    studios: Array<{ name: string }>;
    producers: string[];
    staffs: string[];
    openings: string[];
    endings: string[];
    is_locked: boolean;
    updated_at: string;
    created_at: string;
    episode_count: number;
};
