# Generated by Django 4.1.4 on 2022-12-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_tokens"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tokens",
            new_name="Token",
        ),
    ]
