# Generated by Django 4.1.1 on 2022-09-23 05:23

import apps.user.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.user.models.FileField.avatar,
            ),
        ),
    ]
