# Generated by Django 4.1.4 on 2022-12-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_tokens_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="token",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                max_length=150, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.RemoveField(
            model_name="token",
            name="id",
        ),
    ]
