# Generated by Django 4.1.1 on 2022-09-23 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username_discriminator",
            field=models.BigIntegerField(
                blank=True,
                help_text="Optional. 4 characters or fewer. If not provided a random `username_discriminator` will be selected.",
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(4),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
