# Generated by Django 5.0 on 2024-03-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customuser_username'),
        ('user', '0008_remove_customuser_created_at'),
    ]

    operations = [
    ]
