# Generated by Django 4.0.4 on 2022-04-19 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = []

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeCommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("comment_added", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Episode Comment",
                "ordering": ("-comment_added",),
            },
        ),
        migrations.CreateModel(
            name="EpisodeTimeStampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("episode_number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Episode Timestamp",
            },
        ),
        migrations.CreateModel(
            name="EpisodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_name", models.CharField(db_index=True, max_length=1024)),
                (
                    "episode_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "episode_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "episode_summary",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("episode_number", models.BigIntegerField(default=0)),
                (
                    "episode_comments",
                    models.ManyToManyField(blank=True, to="anime.episodecommentmodel"),
                ),
                (
                    "episode_timestamps",
                    models.ManyToManyField(
                        blank=True, to="anime.episodetimestampmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode",
            },
        ),
        migrations.CreateModel(
            name="AnimeGenreModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.CharField(db_index=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Genre",
            },
        ),
        migrations.CreateModel(
            name="AnimeProducerModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Producer",
            },
        ),
        migrations.CreateModel(
            name="AnimeThemeModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(db_index=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Theme",
            },
        ),
        migrations.CreateModel(
            name="AnimeStudioModel",
            fields=[
                (
                    "mal_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("type", models.CharField(db_index=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Anime Studio",
            },
        ),
        migrations.CreateModel(
            name="AnimeSynonymModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Anime Synonym",
            },
        ),
        migrations.CreateModel(
            name="AnimeCharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=1024, unique=True)),
            ],
            options={
                "verbose_name": "Anime Characters",
            },
        ),
        migrations.CreateModel(
            name="AnimeInfoModel",
            fields=[
                ("anime_name", models.CharField(db_index=True, max_length=1024)),
                ("mal_id", models.IntegerField(unique=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("anime_aired_from", models.DateTimeField(blank=True, null=True)),
                ("anime_aired_to", models.DateTimeField(blank=True, null=True)),
                (
                    "anime_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "anime_name_japanese",
                    models.CharField(db_index=True, max_length=1024, null=True),
                ),
                (
                    "anime_source",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("anime_background", models.TextField(blank=True, null=True)),
                ("anime_synopsis", models.TextField(blank=True, null=True)),
                (
                    "anime_rating",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "anime_episodes",
                    models.ManyToManyField(blank=True, to="anime.episodemodel"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anime_genres",
                    models.ManyToManyField(blank=True, to="anime.animegenremodel"),
                ),
                (
                    "anime_themes",
                    models.ManyToManyField(blank=True, to="anime.animethememodel"),
                ),
                (
                    "anime_studios",
                    models.ManyToManyField(blank=True, to="anime.animestudiomodel"),
                ),
                (
                    "anime_producers",
                    models.ManyToManyField(blank=True, to="anime.animeproducermodel"),
                ),
                (
                    "anime_name_synonyms",
                    models.ManyToManyField(blank=True, to="anime.animesynonymmodel"),
                ),
            ],
            options={
                "verbose_name": "Anime",
            },
        ),
        migrations.CreateModel(
            name="AnimeRecommendationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_url", models.URLField(unique=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anime.animeinfomodel",
                    ),
                ),
                ("anime", models.IntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Anime Recommendations",
            },
        ),
    ]
