# Generated by Django 4.0.4 on 2022-04-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_alter_animecharactermodel_character_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animerecommendationmodel",
            options={"verbose_name": "Anime Recommendation"},
        ),
        migrations.AlterField(
            model_name="animerecommendationmodel",
            name="anime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="anime",
                to="anime.animeinfomodel",
            ),
        ),
        migrations.AlterField(
            model_name="animerecommendationmodel",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="entry",
                to="anime.animeinfomodel",
            ),
        ),
    ]
