# Generated by Django 4.0.3 on 2022-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_animeinfomodel_anime_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='animeinfomodel',
            name='anime_name_japanese',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='animesynonymmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
