# Generated by Django 4.1.1 on 2022-09-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_alter_episodemodel_episode_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={"verbose_name": "Episode Comment"},
        ),
    ]
