# Generated by Django 4.0.3 on 2022-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_alter_animegenremodel_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeCharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimeRecommendationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField()),
                ("mal_url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_recommendations",
            field=models.ManyToManyField(
                blank=True, to="anime.animerecommendationmodel"
            ),
        ),
    ]
