# Generated by Django 4.0.3 on 2022-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0006_alter_animecharactermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animecharactermodel",
            name="mal_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animecharactermodel",
            name="name",
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="animegenremodel",
            name="mal_id",
            field=models.IntegerField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="animegenremodel",
            name="type",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="animeproducermodel",
            name="mal_id",
            field=models.IntegerField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="animerecommendationmodel",
            name="mal_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animerecommendationmodel",
            name="mal_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="animestudiomodel",
            name="mal_id",
            field=models.IntegerField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="animestudiomodel",
            name="type",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="mal_id",
            field=models.IntegerField(
                db_index=True, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="type",
            field=models.CharField(db_index=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_name",
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
