# Generated by Django 4.0.3 on 2022-04-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0007_alter_animecharactermodel_mal_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animecharactermodel",
            options={"verbose_name": "Anime Characters"},
        ),
        migrations.AlterModelOptions(
            name="animegenremodel",
            options={"verbose_name": "Anime Genre"},
        ),
        migrations.AlterModelOptions(
            name="animeproducermodel",
            options={"verbose_name": "Anime Producer"},
        ),
        migrations.AlterModelOptions(
            name="animerecommendationmodel",
            options={"verbose_name": "Anime Recommendations"},
        ),
        migrations.AlterModelOptions(
            name="animestudiomodel",
            options={"verbose_name": "Anime Studio"},
        ),
        migrations.AlterModelOptions(
            name="animesynonymmodel",
            options={"verbose_name": "Anime Synonym"},
        ),
        migrations.AlterModelOptions(
            name="animethememodel",
            options={"verbose_name": "Anime Theme"},
        ),
        migrations.AlterModelOptions(
            name="episodemodel",
            options={"verbose_name": "Episode"},
        ),
    ]
