# Generated by Django 4.0.4 on 2022-04-24 02:54

import apps.anime.models.episode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0008_episodetimestampmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_number", models.BigIntegerField(default=0)),
                ("episode_name", models.CharField(db_index=True, max_length=1024)),
                (
                    "episode_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.anime.models.episode.FileField.episode_cover,
                    ),
                ),
                (
                    "episode_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.anime.models.episode.FileField.episode_upload,
                    ),
                ),
                (
                    "episode_summary",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "episode_comments",
                    models.ManyToManyField(blank=True, to="anime.episodecommentmodel"),
                ),
                (
                    "episode_timestamps",
                    models.ManyToManyField(
                        blank=True, to="anime.episodetimestampmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode",
            },
        ),
    ]
