# Generated by Django 4.0.3 on 2022-04-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0008_alter_animecharactermodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeinfomodel",
            options={"verbose_name": "Anime"},
        ),
        migrations.RemoveField(
            model_name="animerecommendationmodel",
            name="mal_id",
        ),
        migrations.AddField(
            model_name="animerecommendationmodel",
            name="entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="anime.animeinfomodel",
            ),
        ),
    ]
