# Generated by Django 4.0.4 on 2022-04-25 00:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0011_animerecommendationmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimeRecommendationModel",
        ),
    ]
