# Generated by Django 4.0.4 on 2022-04-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0012_delete_animerecommendationmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_recommendation",
            field=models.ManyToManyField(blank=True, to="anime.animeinfomodel"),
        ),
    ]
