# Generated by Django 4.0.4 on 2022-04-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0013_animeinfomodel_anime_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodetimestampmodel",
            name="episode_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="anime.episodemodel"
            ),
        ),
    ]
