# Generated by Django 4.0.3 on 2022-04-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0014_rename_mal_id_animerecommendationmodel_anime_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animerecommendationmodel",
            name="anime_id",
        ),
        migrations.AddField(
            model_name="animerecommendationmodel",
            name="anime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anime_id",
                to="anime.animeinfomodel",
            ),
        ),
    ]
