# Generated by Django 4.0.4 on 2022-04-25 01:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0015_rename_episode_number_episodetimestampmodel_episode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_name",
            field=models.CharField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="animeinfomodel",
            name="anime_name_japanese",
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
