# Generated by Django 4.0.4 on 2022-04-25 07:11
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0016_alter_animeinfomodel_anime_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodetimestampmodel",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="anime.episodemodel"
            ),
        ),
    ]
