# Generated by Django 4.0.4 on 2022-04-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0019_episodetimestampmodel_episode_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodetimestampmodel",
            name="episode_number",
        ),
    ]
