# Generated by Django 4.0.4 on 2022-04-25 07:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0020_remove_episodetimestampmodel_episode_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodetimestampmodel",
            name="episode_number",
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
    ]
