# Generated by Django 4.0.4 on 2022-04-25 11:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0023_alter_episodetimestampmodel_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeinfomodel",
            name="anime_characters",
            field=models.ManyToManyField(blank=True, to="anime.animecharactermodel"),
        ),
    ]
