"""create inital tables

Revision ID: 3e86374fc933
Revises: 
Create Date: 2022-10-13 10:08:57.692897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e86374fc933"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=True),
        sa.Column("last_login", sa.DATETIME(), nullable=True),
        sa.Column("is_superuser", sa.BOOLEAN(), nullable=True),
        sa.Column("username", sa.VARCHAR(length=150), nullable=True),
        sa.Column("first_name", sa.VARCHAR(length=150), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=150), nullable=True),
        sa.Column("email", sa.VARCHAR(length=254), nullable=True),
        sa.Column("is_staff", sa.BOOLEAN(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("username_discriminator", sa.INTEGER(), nullable=True),
        sa.Column("avatar", sa.VARCHAR(length=150), nullable=True),
        sa.Column("avatar_provider", sa.VARCHAR(), nullable=True),
        sa.Column("date_joined", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
