"""empty message

Revision ID: 83339d682fd4
Revises: 3e86374fc933
Create Date: 2022-10-13 10:16:33.417281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83339d682fd4"
down_revision = "3e86374fc933"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
