# Generated by Django 4.1 on 2022-08-11 04:56

import apps.api.v1.characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=1024, unique=True)),
                (
                    "character_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=apps.api.v1.characters.models.FileField.anime_charater,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anime Character",
            },
        ),
    ]
