# Generated by Django 4.1 on 2022-08-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0003_delete_animecharactermodel_and_more"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnimeCharacterModel",
            new_name="CharacterModel",
        ),
    ]
