from .anime_character import AnimeCharacterModel
from .anime_genre import AnimeGenreModel
from .anime_info import AnimeInfoModel
from .anime_producer import AnimeProducerModel
from .anime_recommendations import AnimeRecommendationModel
from .anime_studio import AnimeStudioModel
from .anime_synonym import AnimeSynonymModel
from .anime_theme import AnimeThemeModel
from .episode_comment import EpisodeCommentModel
from .episode_timestamp import EpisodeTimestampModel
from .episode import EpisodeModel
