# Generated by Django 4.2 on 2023-01-15 03:14

import core.storages
import dynamic_filenames

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EpisodeCommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("comment_added", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Episode Comment",
            },
        ),
        migrations.CreateModel(
            name="EpisodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_number", models.BigIntegerField(default=0)),
                ("episode_name", models.CharField(max_length=1024)),
                (
                    "episode_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=core.storages.OverwriteStorage(),
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="/episode_cover/{uuid:s}{ext}"
                        ),
                    ),
                ),
                (
                    "episode_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=core.storages.OverwriteStorage(),
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="/episode/{uuid:s}{ext}"
                        ),
                    ),
                ),
                ("episode_summary", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
            },
        ),
        migrations.CreateModel(
            name="EpisodeTimestampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.IntegerField(default=0)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="episodes.episodemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode Timestamp",
            },
        ),
    ]
