# Generated by Django 4.1.5 on 2023-01-14 04:35

import core.storages
import dynamic_filenames

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodemodel",
            options={"verbose_name": "Episode", "verbose_name_plural": "Episodes"},
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/episode_cover/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/episode/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_name",
            field=models.CharField(max_length=1024),
        ),
    ]
