# Generated by Django 4.1.7 on 2023-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0002_episodemodel_episode_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodecommentmodel",
            name="depth",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="episodecommentmodel",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="episodecommentmodel",
            name="path",
            field=models.CharField(default="", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
