# Generated by Django 4.2b1 on 2023-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodemodel",
            name="doodstream_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="fembed_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="mp4_upload_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="streamsb_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="streamtape_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
