# Generated by Django 4.1.7 on 2023-02-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0003_episodemodel_doodstream_url_episodemodel_fembed_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="streamsb_url",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="streamsb_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
