# Generated by Django 4.1.7 on 2023-03-04 03:39

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import (
    HStoreExtension,
)


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0004_remove_episodemodel_streamsb_url_and_more"),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name="episodemodel",
            name="doodstream_url",
        ),
        migrations.RemoveField(
            model_name="episodemodel",
            name="fembed_url",
        ),
        migrations.RemoveField(
            model_name="episodemodel",
            name="mp4_upload_url",
        ),
        migrations.RemoveField(
            model_name="episodemodel",
            name="streamsb_id",
        ),
        migrations.RemoveField(
            model_name="episodemodel",
            name="streamtape_url",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="providers",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict
            ),
        ),
    ]
