# Generated by Django 4.2 on 2023-04-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("episodes", "0005_remove_episodecommentmodel_comment_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.image"
            ),
        ),
    ]
