# Generated by Django 4.1.7 on 2023-03-05 14:06

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0005_remove_episodemodel_doodstream_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="episode_cover",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="episode_thumbnail",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="thumbnail/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="episode/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
