# Generated by Django 4.2.4 on 2023-08-30 16:27

import django.contrib.postgres.indexes
import django_ltree.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_ltree", "__latest__"),
        ("episodes", "0005_remove_episodecommentmodel_comment_added_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={},
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_ancestors_count",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_ancestors_pks",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_children_count",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_children_pks",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_depth",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_descendants_count",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_descendants_pks",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_index",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_level",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_order",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_parent",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_priority",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_siblings_count",
        ),
        migrations.RemoveField(
            model_name="episodecommentmodel",
            name="tn_siblings_pks",
        ),
        migrations.AddField(
            model_name="episodecommentmodel",
            name="path",
            field=django_ltree.fields.PathField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="episodecommentmodel",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["path"], name="episodes_ep_path_a19128_gist"
            ),
        ),
    ]
