# Generated by Django 4.1.7 on 2023-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0006_remove_episodemodel_episode_cover_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episodemodel",
            name="episode_file",
        ),
        migrations.AddField(
            model_name="episodemodel",
            name="episode_length",
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
