# Generated by Django 4.2.4 on 2023-08-31 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0007_remove_episodetimestampmodel_episode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodecommentmodel",
            options={
                "verbose_name": "Episode Comment",
                "verbose_name_plural": "Episode Comments",
            },
        ),
    ]
