# Generated by Django 5.0b1 on 2023-10-29 05:51

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("episodes", "0008_alter_episodecommentmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodecommentmodel",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
        migrations.AlterField(
            model_name="episodetimestampmodel",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
