# Generated by Django 4.2 on 2023-04-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mal_id", models.IntegerField(null=True, unique=True)),
                ("kitsu_id", models.IntegerField(null=True, unique=True)),
                ("anilist_id", models.IntegerField(null=True, unique=True)),
                ("name", models.CharField(max_length=1024)),
                ("name_kanji", models.CharField(blank=True, max_length=1024, null=True)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "character_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="images.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
            },
        ),
    ]
