# Generated by Django 4.2 on 2023-01-15 03:14

import core.storages
import dynamic_filenames

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(null=True, unique=True)),
                ("kitsu_id", models.IntegerField(null=True, unique=True)),
                ("anilist_id", models.IntegerField(null=True, unique=True)),
                ("name", models.CharField(max_length=1024)),
                ("name_kanji", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "character_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=core.storages.OverwriteStorage(),
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="characters/{uuid:s}{ext}"
                        ),
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
            },
        ),
    ]
