# Generated by Django 4.2a1 on 2023-02-05 15:07

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="character_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="characters/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
