# Generated by Django 4.2 on 2023-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0002_charactermodel_created_at_charactermodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermodel",
            name="is_locked",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
