# Generated by Django 4.2 on 2023-04-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("characters", "0002_charactermodel_created_at_charactermodel_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="character_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="images.image",
            ),
        ),
    ]
