# Generated by Django 4.1.1 on 2022-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_charactermodel_character_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_dictionary", models.JSONField()),
                ("logs", models.TextField()),
            ],
        ),
    ]
