# Generated by Django 4.1.1 on 2022-10-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_characterlogmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterLogModel",
        ),
    ]
