# Generated by Django 4.1.2 on 2022-10-29 02:59

import core.storages
import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_delete_characterlogmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="character_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/anime_charaters{ext}"
                ),
            ),
        ),
    ]
