# Generated by Django 4.1.5 on 2023-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0007_alter_charactermodel_character_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="character_image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="",
            ),
        ),
    ]
