# Generated by Django 4.1.5 on 2023-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0010_alter_charactermodel_character_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactermodel",
            name="anilist_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="charactermodel",
            name="kitsu_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="charactermodel",
            name="mal_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="charactermodel",
            name="name",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="charactermodel",
            name="name_kanji",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
