# Generated by Django 4.0.2 on 2022-02-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capturemodel",
            old_name="vimejs_volume",
            new_name="video_volume",
        ),
    ]
