# Generated by Django 4.1.1 on 2022-09-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anilistmodel",
            options={"verbose_name": "AniList", "verbose_name_plural": "AniList"},
        ),
        migrations.AlterModelOptions(
            name="kitsumodel",
            options={"verbose_name": "Kitsu", "verbose_name_plural": "Kitsu"},
        ),
        migrations.AlterModelOptions(
            name="malmodel",
            options={
                "verbose_name": "MyAnimeList",
                "verbose_name_plural": "MyAnimeList",
            },
        ),
    ]
