# Generated by Django 4.1.7 on 2023-03-14 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_token_unique_together"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
