# Generated by Django 4.1.7 on 2023-03-26 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_customuser_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="ip",
        ),
    ]
