# Generated by Django 4.2.5 on 2023-09-09 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_customuser_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
    ]
