# Generated by Django 5.1 on 2024-09-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_created_at_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
