# Generated by Django 4.2a1 on 2023-01-18 12:05

import django_better_admin_arrayfield.models.fields
import dynamic_filenames

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.contrib.postgres.operations import BtreeGinExtension, HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0001_initial"),
        ("producers", "0001_initial"),
        ("studios", "0001_initial"),
        ("episodes", "0001_initial"),
    ]

    operations = [
        HStoreExtension(),
        BtreeGinExtension(),
        migrations.CreateModel(
            name="AnimeGenreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(unique=True)),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("type", models.CharField(default="", max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Anime Genre",
            },
        ),
        migrations.CreateModel(
            name="AnimeThemeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(unique=True)),
                ("name", models.CharField(default="", max_length=50, unique=True)),
                ("type", models.CharField(default="", max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Anime Theme",
            },
        ),
        migrations.CreateModel(
            name="AnimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mal_id", models.IntegerField(null=True, unique=True)),
                ("anilist_id", models.IntegerField(null=True, unique=True)),
                ("kitsu_id", models.IntegerField(null=True, unique=True)),
                ("anime_name", models.CharField(max_length=1024, unique=True)),
                ("anime_name_japanese", models.CharField(max_length=1024, null=True)),
                ("anime_source", models.CharField(blank=True, max_length=128, null=True)),
                ("anime_aired_from", models.DateTimeField(blank=True, null=True)),
                ("anime_aired_to", models.DateTimeField(blank=True, null=True)),
                (
                    "anime_banner",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_patten="/anime_banner{ext}"
                        ),
                    ),
                ),
                (
                    "anime_cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="/anime_cover{ext}"
                        ),
                    ),
                ),
                ("anime_synopsis", models.TextField(blank=True, null=True)),
                ("anime_background", models.TextField(blank=True, null=True)),
                ("anime_rating", models.CharField(blank=True, max_length=50, null=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "anime_characters",
                    models.ManyToManyField(blank=True, to="characters.charactermodel"),
                ),
                (
                    "anime_episodes",
                    models.ManyToManyField(blank=True, to="episodes.episodemodel"),
                ),
                (
                    "anime_genres",
                    models.ManyToManyField(blank=True, to="anime.animegenremodel"),
                ),
                (
                    "anime_producers",
                    models.ManyToManyField(blank=True, to="producers.producermodel"),
                ),
                (
                    "anime_recommendation",
                    models.ManyToManyField(blank=True, to="anime.animemodel"),
                ),
                (
                    "anime_studios",
                    models.ManyToManyField(blank=True, to="studios.studiomodel"),
                ),
                (
                    "anime_themes",
                    models.ManyToManyField(blank=True, to="anime.animethememodel"),
                ),
                (
                    "anime_name_synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anime",
            },
        ),
        django.contrib.postgres.operations.BtreeGinExtension(),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_patten="/anime_banner/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/anime_cover/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="animemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["anime_name", "anime_name_japanese", "anime_name_synonyms"],
                name="anime_anime_anime_n_3ed388_gin",
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_synonyms",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        django.contrib.postgres.operations.HStoreExtension(),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_rating",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_synonyms",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_japanese",
            field=models.CharField(default="", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anilist_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_japanese",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="mal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_theme_endings",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_theme_openings",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict
            ),
        ),
    ]
