# Generated by Django 4.2a1 on 2023-01-22 04:52

import core.storages
from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_patten="/banner/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/cover/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
