# Generated by Django 4.1.5 on 2023-01-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animegenremodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animethememodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animegenremodel",
            name="mal_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="animegenremodel",
            name="name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="animegenremodel",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="animesynonymmodel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="mal_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="name",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
