# Generated by Django 4.1.7 on 2023-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0001_initial"),
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="staffs",
            field=models.ManyToManyField(blank=True, to="staffs.staffmodel"),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="rating",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
