# Generated by Django 4.2 on 2023-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("anime", "0001_initial"),
        ("episodes", "0001_initial"),
        ("studios", "0001_initial"),
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="anime_episodes",
            field=models.ManyToManyField(blank=True, to="episodes.episodemodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenremodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_name_synonyms",
            field=models.ManyToManyField(blank=True, to="anime.animesynonymmodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_producers",
            field=models.ManyToManyField(blank=True, to="producers.producermodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_recommendation",
            field=models.ManyToManyField(blank=True, to="anime.animemodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_studios",
            field=models.ManyToManyField(blank=True, to="studios.studiomodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_themes",
            field=models.ManyToManyField(blank=True, to="anime.animethememodel"),
        ),
    ]
