# Generated by Django 4.2 on 2023-04-14 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("anime", "0001_initial"),
        ("images", "0001_initial"),
        ("staffs", "0001_initial"),
        ("producers", "0001_initial"),
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="episodes",
            field=models.ManyToManyField(blank=True, to="episodes.episodemodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="genres",
            field=models.ManyToManyField(blank=True, to="anime.animegenremodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="name_synonyms",
            field=models.ManyToManyField(blank=True, to="anime.animenamesynonymmodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="openings",
            field=models.ManyToManyField(blank=True, to="anime.animeopeningmodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="producers",
            field=models.ManyToManyField(
                blank=True, related_name="producers", to="producers.producermodel"
            ),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="recommendations",
            field=models.ManyToManyField(blank=True, to="anime.animemodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="staffs",
            field=models.ManyToManyField(blank=True, to="staffs.staffmodel"),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="studios",
            field=models.ManyToManyField(
                blank=True, related_name="studios", to="producers.producermodel"
            ),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="themes",
            field=models.ManyToManyField(blank=True, to="anime.animethememodel"),
        ),
        migrations.AddField(
            model_name="animeendingmodel",
            name="thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.image"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="animeopeningmodel",
            unique_together={("entry", "name", "url")},
        ),
        migrations.AlterUniqueTogether(
            name="animeendingmodel",
            unique_together={("entry", "name", "url")},
        ),
    ]
