# Generated by Django 4.1 on 2022-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CharacterModel",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_characters",
            field=models.ManyToManyField(blank=True, to="characters.charactermodel"),
        ),
    ]
