# Generated by Django 4.2 on 2023-01-15 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animemodel",
            name="anime_name_synonyms",
        ),
        migrations.DeleteModel(
            name="AnimeSynonymModel",
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_name_synonyms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
