# Generated by Django 4.2a1 on 2023-01-23 14:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_alter_animemodel_banner_alter_animemodel_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="banner_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
    ]
