# Generated by Django 4.1.5 on 2023-01-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_animegenremodel_id_animethememodel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="type",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="type",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
