# Generated by Django 4.2a1 on 2023-01-23 16:13

import colorfield.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_animemodel_banner_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="cover_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
    ]
