# Generated by Django 4.2 on 2023-01-15 05:59

import dynamic_filenames

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_remove_animemodel_anime_name_synonyms_and_more"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_patten="/anime_banner/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/anime_cover/{uuid:s}{ext}"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="animemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["anime_name", "anime_name_japanese", "anime_name_synonyms"],
                name="anime_anime_anime_n_3ed388_gin",
            ),
        ),
    ]
