# Generated by Django 4.1.7 on 2023-03-22 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_alter_animemodel_rating"),
        ("anime", "0003_remove_animemodel_theme_endings_and_more"),
    ]

    operations = []
