# Generated by Django 4.1.7 on 2023-03-03 11:22

from django.db import migrations, models
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_alter_animemodel_name_alter_animemodel_name_japanese_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="banner/{uuid:s}{ext}"
                ),
            ),
        ),
    ]
