# Generated by Django 4.1.7 on 2023-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_remove_animemodel_theme_endings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animeendingmodel",
            options={
                "verbose_name": "Anime Ending",
                "verbose_name_plural": "Anime Endings",
            },
        ),
        migrations.AlterModelOptions(
            name="animeopeningmodel",
            options={
                "verbose_name": "Anime Opening",
                "verbose_name_plural": "Anime Openings",
            },
        ),
        migrations.AddField(
            model_name="animeendingmodel",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="animeopeningmodel",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
