# Generated by Django 4.1.7 on 2023-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0003_remove_animemodel_theme_endings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeendingmodel",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="animeopeningmodel",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
