# Generated by Django 4.1.7 on 2023-03-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0004_alter_animegenremodel_type_alter_animemodel_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anilist_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="mal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
