# Generated by Django 4.1.1 on 2022-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0004_alter_episodecommentmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_japanese",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
