# Generated by Django 4.1.2 on 2022-10-29 02:59

import core.storages
import dynamic_filenames

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0005_alter_animemodel_anime_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anime_banner",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_patten="/anime_banner{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/anime_cover{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_cover",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="/episode_cover{ext}"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="episodemodel",
            name="episode_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=core.storages.OverwriteStorage(),
                upload_to=dynamic_filenames.FilePattern(filename_pattern="/episode{ext}"),
            ),
        ),
    ]
