# Generated by Django 4.2 on 2023-01-17 03:02

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0005_alter_animemodel_anime_name_synonyms"),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name="animemodel",
            name="anime_theme_endings",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="animemodel",
            name="anime_theme_openings",
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_rating",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
