# Generated by Django 4.2a1 on 2023-01-18 08:52

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0006_animemodel_anime_theme_endings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_synonyms",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(max_length=1024),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
