# Generated by Django 4.2 on 2023-04-13 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0006_merge_20230326_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="animemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
