# Generated by Django 4.2a1 on 2023-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0007_alter_animemodel_anime_name_synonyms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_japanese",
            field=models.CharField(default="", max_length=1024, null=True),
        ),
    ]
