# Generated by Django 4.2a1 on 2023-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0008_alter_animemodel_anime_name_japanese"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anilist_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_name_japanese",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="kitsu_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
