# Generated by Django 4.2 on 2023-04-14 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("anime", "0008_rename_updated_animemodel_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animemodel",
            name="banner_background_color",
        ),
        migrations.RemoveField(
            model_name="animemodel",
            name="cover_background_color",
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banner",
                to="images.imagewithbrightnessandbackgroundcolor",
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover",
                to="images.imagewithbrightnessandbackgroundcolor",
            ),
        ),
    ]
