# Generated by Django 4.2 on 2023-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0008_rename_updated_animemodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="animegenremodel",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
