# Generated by Django 4.2 on 2023-04-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
        ("anime", "0009_remove_animemodel_banner_background_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeendingmodel",
            name="thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.image"
            ),
        ),
        migrations.AlterField(
            model_name="animeopeningmodel",
            name="thumbnail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.image"
            ),
        ),
    ]
