# Generated by Django 4.2a1 on 2023-01-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0009_alter_animemodel_anilist_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="mal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
