# Generated by Django 4.2a1 on 2023-01-18 09:06

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0010_alter_animemodel_mal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="anime_theme_endings",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="anime_theme_openings",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, default=dict
            ),
        ),
    ]
