# Generated by Django 4.2.4 on 2023-08-29 04:12

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0018_alter_animenamesynonymmodel_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="animemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "name_japanese"],
                name="anime_name|name_japanese_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
