# Generated by Django 4.2.4 on 2023-08-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0019_animemodel_anime_name_name_japanese_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="type",
            field=models.CharField(
                choices=[("Anime", "anime"), ("Manga", "manga")], default="", max_length=50
            ),
        ),
    ]
