# Generated by Django 5.0rc1 on 2023-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0024_animecommentmodel_animemodel_comments_and_more"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="comments",
            field=models.ManyToManyField(blank=True, to="comments.commentmodel"),
        ),
        migrations.DeleteModel(
            name="AnimeCommentModel",
        ),
    ]
