# Generated by Django 5.0.2 on 2024-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0025_alter_animemodel_comments_delete_animecommentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="is_locked",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="is_locked",
            field=models.BooleanField(db_default=False),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="is_locked",
            field=models.BooleanField(db_default=False),
        ),
    ]
