# Generated by Django 5.1.4 on 2025-01-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='candidate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='sdp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
