# Generated by Django 5.1.4 on 2025-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_rename_last_seen_peer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='info_hash',
            field=models.CharField(unique=True),
        ),
    ]
