# Generated by Django 5.1.4 on 2025-01-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0002_peer_candidate_peer_sdp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('torrent', 'ip', 'port')},
        ),
    ]
