# Generated by Django 5.1.4 on 2025-01-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0003_alter_torrent_info_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='is_seeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('torrent', 'ip', 'port')},
        ),
    ]
