version: 2

build:
    os: ubuntu-latest
    tools:
        python: latest
    jobs:
        pre_create_environment:
            - asdf plugin add uv
            - asdf install uv latest
            - asdf global uv latest

        create_environment:
            - cd docs && uv venv

        install:
            - cd docs && uv sync

        build:
            html:
                - cd docs && uv run zensical build --clean

        post_build:
            - mkdir -p $READTHEDOCS_OUTPUT/html/
            - cd docs && cp --recursive site/* $READTHEDOCS_OUTPUT/html/