{'__annotations__': {'_get_current_object': 't.Callable[[], T]'},
 '__dict__': {'_accept': functools.partial(<bound method ASGIWebsocketConnection.accept_connection of <quart.asgi.ASGIWebsocketConnection object at 0x0000019A83BF06E0>>, <bound method WSStream.app_send of <hypercorn.protocol.ws_stream.WSStream object at 0x0000019A83BF0AD0>>),
              '_close': functools.partial(<bound method ASGIWebsocketConnection.close_connection of <quart.asgi.ASGIWebsocketConnection object at 0x0000019A83BF06E0>>, <bound method WSStream.app_send of <hypercorn.protocol.ws_stream.WSStream object at 0x0000019A83BF0AD0>>),
              '_parsed_content_type': ('', {}),
              '_receive': <bound method Queue.get of <Queue at 0x19a83bd8f50 maxsize=0 tasks=1>>,
              '_send': functools.partial(<bound method ASGIWebsocketConnection.send_data of <quart.asgi.ASGIWebsocketConnection object at 0x0000019A83BF06E0>>, <bound method WSStream.app_send of <hypercorn.protocol.ws_stream.WSStream object at 0x0000019A83BF0AD0>>),
              '_subprotocols': [],
              'accept_charsets': CharsetAccept([]),
              'accept_encodings': Accept([('gzip', 1), ('deflate', 1), ('br', 1), ('zstd', 1)]),
              'accept_languages': LanguageAccept([('en-US', 1), ('en', 0.5)]),
              'accept_mimetypes': MIMEAccept([('*/*', 1)]),
              'access_route': ImmutableList(['127.0.0.1']),
              'args': ImmutableMultiDict([]),
              'authorization': None,
              'base_url': 'ws://localhost:5000/',
              'cache_control': <RequestCacheControl no-cache=None>,
              'content_length': None,
              'cookies': ImmutableMultiDict([]),
              'full_path': '/?',
              'headers': Headers([('Remote-Addr', '127.0.0.1'), ('Host', 'localhost:5000'), ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0'), ('Accept', '*/*'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate, br, zstd'), ('Sec-Websocket-Version', '13'), ('Origin', 'http://127.0.0.1:5500'), ('Sec-Websocket-Extensions', 'permessage-deflate'), ('Sec-Websocket-Key', 'dzplnzube2mIvh/7w6cYBA=='), ('Dnt', '1'), ('Connection', 'keep-alive, Upgrade'), ('Sec-Fetch-Dest', 'empty'), ('Sec-Fetch-Mode', 'websocket'), ('Sec-Fetch-Site', 'cross-site'), ('Pragma', 'no-cache'), ('Cache-Control', 'no-cache'), ('Upgrade', 'websocket')]),
              'host': 'localhost:5000',
              'host_url': 'ws://localhost:5000/',
              'http_version': '1.1',
              'if_match': <ETags ''>,
              'if_modified_since': None,
              'if_none_match': <ETags ''>,
              'if_range': <IfRange ''>,
              'if_unmodified_since': None,
              'json_module': <flask.json.provider.DefaultJSONProvider object at 0x0000019A83A0B4D0>,
              'method': 'GET',
              'path': '/',
              'pragma': HeaderSet(['no-cache']),
              'query_string': b'',
              'range': None,
              'remote_addr': '127.0.0.1',
              'root_path': '',
              'root_url': 'ws://localhost:5000/',
              'routing_exception': None,
              'scheme': 'ws',
              'scope': {'asgi': {'spec_version': '2.3', 'version': '3.0'},
                        'client': ('127.0.0.1', 49702),
                        'extensions': {'websocket.http.response': {}},
                        'headers': [(b'host', b'localhost:5000'),
                                    (b'user-agent',
                                     b'Mozilla/5.0 (Windows NT 10.0; Win64; x64'
                                     b'; rv:137.0) Gecko/20100101 Firefox/137.0'),
                                    (b'accept', b'*/*'),
                                    (b'accept-language', b'en-US,en;q=0.5'),
                                    (b'accept-encoding',
                                     b'gzip, deflate, br, zstd'),
                                    (b'sec-websocket-version', b'13'),
                                    (b'origin', b'http://127.0.0.1:5500'),
                                    (b'sec-websocket-extensions',
                                     b'permessage-deflate'),
                                    (b'sec-websocket-key',
                                     b'dzplnzube2mIvh/7w6cYBA=='),
                                    (b'dnt', b'1'),
                                    (b'connection', b'keep-alive, Upgrade'),
                                    (b'sec-fetch-dest', b'empty'),
                                    (b'sec-fetch-mode', b'websocket'),
                                    (b'sec-fetch-site', b'cross-site'),
                                    (b'pragma', b'no-cache'),
                                    (b'cache-control', b'no-cache'),
                                    (b'upgrade', b'websocket')],
                        'http_version': '1.1',
                        'path': '/',
                        'query_string': b'',
                        'raw_path': b'/',
                        'root_path': '',
                        'scheme': 'ws',
                        'server': ('127.0.0.1', 5000),
                        'state': {},
                        'subprotocols': [],
                        'type': 'websocket'},
              'server': ('127.0.0.1', 5000),
              'url': 'ws://localhost:5000/',
              'url_rule': <QuartRule '/' (GET, HEAD, OPTIONS) -> websocket.ws>,
              'user_agent': <UserAgent None/None>,
              'view_args': {}},
 '__doc__': None,
 '__firstlineno__': 388,
 '__module__': 'werkzeug.local',
 '__static_attributes__': (),
 '__weakref__': None,
 '_subprotocols': [],
 'accept_charsets': CharsetAccept([]),
 'accept_encodings': Accept([('gzip', 1), ('deflate', 1), ('br', 1), ('zstd', 1)]),
 'accept_languages': LanguageAccept([('en-US', 1), ('en', 0.5)]),
 'accept_mimetypes': MIMEAccept([('*/*', 1)]),
 'access_control_request_headers': None,
 'access_control_request_method': None,
 'access_route': ImmutableList(['127.0.0.1']),
 'args': ImmutableMultiDict([]),
 'authorization': None,
 'base_url': 'ws://localhost:5000/',
 'blueprint': 'websocket',
 'blueprints': ['websocket'],
 'cache_control': <RequestCacheControl no-cache=None>,
 'content_encoding': None,
 'content_length': None,
 'content_md5': None,
 'content_type': None,
 'cookies': ImmutableMultiDict([]),
 'date': None,
 'endpoint': 'websocket.ws',
 'full_path': '/?',
 'headers': Headers([('Remote-Addr', '127.0.0.1'), ('Host', 'localhost:5000'), ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) Gecko/20100101 Firefox/137.0'), ('Accept', '*/*'), ('Accept-Language', 'en-US,en;q=0.5'), ('Accept-Encoding', 'gzip, deflate, br, zstd'), ('Sec-Websocket-Version', '13'), ('Origin', 'http://127.0.0.1:5500'), ('Sec-Websocket-Extensions', 'permessage-deflate'), ('Sec-Websocket-Key', 'dzplnzube2mIvh/7w6cYBA=='), ('Dnt', '1'), ('Connection', 'keep-alive, Upgrade'), ('Sec-Fetch-Dest', 'empty'), ('Sec-Fetch-Mode', 'websocket'), ('Sec-Fetch-Site', 'cross-site'), ('Pragma', 'no-cache'), ('Cache-Control', 'no-cache'), ('Upgrade', 'websocket')]),
 'host': 'localhost:5000',
 'host_url': 'ws://localhost:5000/',
 'http_version': '1.1',
 'if_modified_since': None,
 'if_range': <IfRange ''>,
 'if_unmodified_since': None,
 'is_json': False,
 'is_secure': False,
 'json_module': <flask.json.provider.DefaultJSONProvider object at 0x0000019A83A0B4D0>,
 'max_forwards': None,
 'method': 'GET',
 'mimetype': '',
 'mimetype_params': {},
 'origin': 'http://127.0.0.1:5500',
 'path': '/',
 'pragma': HeaderSet(['no-cache']),
 'query_string': b'',
 'range': None,
 'referrer': None,
 'remote_addr': '127.0.0.1',
 'requested_subprotocols': [],
 'root_path': '',
 'root_url': 'ws://localhost:5000/',
 'routing_exception': None,
 'scheme': 'ws',
 'scope': {'asgi': {'spec_version': '2.3', 'version': '3.0'},
           'client': ('127.0.0.1', 49702),
           'extensions': {'websocket.http.response': {}},
           'headers': [(b'host', b'localhost:5000'),
                       (b'user-agent',
                        b'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:137.0) '
                        b'Gecko/20100101 Firefox/137.0'),
                       (b'accept', b'*/*'),
                       (b'accept-language', b'en-US,en;q=0.5'),
                       (b'accept-encoding', b'gzip, deflate, br, zstd'),
                       (b'sec-websocket-version', b'13'),
                       (b'origin', b'http://127.0.0.1:5500'),
                       (b'sec-websocket-extensions', b'permessage-deflate'),
                       (b'sec-websocket-key', b'dzplnzube2mIvh/7w6cYBA=='),
                       (b'dnt', b'1'),
                       (b'connection', b'keep-alive, Upgrade'),
                       (b'sec-fetch-dest', b'empty'),
                       (b'sec-fetch-mode', b'websocket'),
                       (b'sec-fetch-site', b'cross-site'),
                       (b'pragma', b'no-cache'),
                       (b'cache-control', b'no-cache'),
                       (b'upgrade', b'websocket')],
           'http_version': '1.1',
           'path': '/',
           'query_string': b'',
           'raw_path': b'/',
           'root_path': '',
           'scheme': 'ws',
           'server': ('127.0.0.1', 5000),
           'state': {},
           'subprotocols': [],
           'type': 'websocket'},
 'script_root': '',
 'server': ('127.0.0.1', 5000),
 'trusted_hosts': None,
 'url': 'ws://localhost:5000/',
 'url_root': 'ws://localhost:5000/',
 'url_rule': <QuartRule '/' (GET, HEAD, OPTIONS) -> websocket.ws>,
 'user_agent': <UserAgent None/None>,
 'view_args': {}}