# Generated by Django 4.0 on 2021-12-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(
                choices=[
                    ("Libravatar", "https://seccdn.libravatar.org/"),
                    ("Gravatar", "https://www.gravatar.com/"),
                ],
                default="https://seccdn.libravatar.org/",
            ),
        ),
    ]
