# Generated by Django 4.0 on 2021-12-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.CharField(
                choices=[
                    ("Libravatar", "https://seccdn.libravatar.org/"),
                    ("Gravatar", "https://www.gravatar.com/"),
                ],
                default="https://seccdn.libravatar.org/",
                max_length=50,
            ),
        ),
    ]
