# Generated by Django 4.0 on 2021-12-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_customuser_language_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="language_choice",
        ),
    ]
