# Generated by Django 4.1.1 on 2022-10-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CharacterLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_dictionary", models.JSONField()),
                ("logs", models.TextField()),
            ],
        ),
    ]
