# Generated by Django 5.0rc1 on 2023-12-05 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentmodel",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
    ]
