# Generated by Django 5.0rc1 on 2023-12-05 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_commentmodel_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commentmodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
