# Generated by Django 5.0 on 2023-12-07 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_commentmodel_dislikes_alter_commentmodel_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentmodel",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="commentmodel",
            name="likes",
        ),
        migrations.AddField(
            model_name="commentmodel",
            name="downvotes",
            field=models.ManyToManyField(
                blank=True, related_name="downvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commentmodel",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="upvotes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
