# Generated by Django 5.0.2 on 2024-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_remove_commentmodel_dislikes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
