# Generated by Django 5.0.2 on 2024-02-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_reportedcommentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportedcommentmodel",
            name="reported_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
