# Generated by Django 5.0.2 on 2024-02-24 02:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0009_reportedcommentmodel_reported_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportedcommentmodel",
            old_name="reported_user",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="reportedcommentmodel",
            name="reported_at",
        ),
        migrations.AddField(
            model_name="reportedcommentmodel",
            name="created_at",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
