# Generated by Django 5.0.2 on 2024-02-24 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0012_alter_reportedcommentmodel_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportedcommentmodel",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="reportedcommentmodel",
            name="user",
        ),
        migrations.AddField(
            model_name="reportedcommentmodel",
            name="reports",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
