# Generated by Django 4.2.4 on 2023-08-29 04:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0005_alter_staffmodel_is_locked"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="staffalternatenamemodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="staff_alternate_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="staffmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "given_name", "family_name"],
                name="staff_name_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
