# Generated by Django 4.0.2 on 2022-02-14 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("_capture", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capturemodel",
            options={"verbose_name": "User Info Capture Model"},
        ),
        migrations.AlterField(
            model_name="capturemodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
