# Generated by Django 4.2a1 on 2023-01-22 11:08

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token",
            field=models.CharField(
                default=functools.partial(
                    django.utils.crypto.get_random_string, *(16,), **{}
                ),
                editable=False,
                max_length=16,
                unique=True,
            ),
        ),
    ]
