# Generated by Django 4.2a1 on 2023-01-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_token_token"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="token",
            index=models.Index(fields=["token"], name="api_token_token_5cc0f7_idx"),
        ),
    ]
