# Generated by Django 4.2 on 2023-04-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0004_rename_japanese_title_producermodel_name_japanese"),
    ]

    operations = [
        migrations.AddField(
            model_name="producermodel",
            name="is_locked",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
