# Generated by Django 5.0.2 on 2024-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0008_alter_producermodel_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producermodel",
            name="is_locked",
            field=models.BooleanField(db_default=False),
        ),
    ]
