# Generated by Django 4.0.7 on 2022-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
