# Generated by Django 4.0.4 on 2022-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_kitsu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mal_token",
        ),
        migrations.AddField(
            model_name="user",
            name="mal",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
