# Generated by Django 4.0.4 on 2022-05-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_kitsu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kitsu",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mal_token",
        ),
        migrations.CreateModel(
            name="MalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", django_unixdatetimefield.fields.UnixDateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KitsuUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", django_unixdatetimefield.fields.UnixDateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnilistUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", django_unixdatetimefield.fields.UnixDateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
