# Generated by Django 4.0.4 on 2022-05-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_kitsu_remove_user_mal_token_maluser_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MalUser",
            new_name="Anilist",
        ),
        migrations.RenameModel(
            old_name="KitsuUser",
            new_name="Kitsu",
        ),
        migrations.RenameModel(
            old_name="AnilistUser",
            new_name="Mal",
        ),
    ]
