# Generated by Django 4.0.4 on 2022-05-25 02:34

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_mal_token_user_mal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mal",
        ),
        migrations.AddField(
            model_name="user",
            name="myanimelist",
            field=models.JSONField(
                blank=True, default=apps.user.models.default_myanimelist, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="kitsu",
            field=models.JSONField(
                blank=True, default=apps.user.models.default_kitsu, null=True
            ),
        ),
    ]
