# Generated by Django 4.0.4 on 2022-05-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("anime", "0025_alter_animecharactermodel_options"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0008_rename_maluser_anilist_rename_kitsuuser_kitsu_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mal",
            new_name="AnilistModel",
        ),
        migrations.RenameModel(
            old_name="Kitsu",
            new_name="KitsuModel",
        ),
        migrations.RenameModel(
            old_name="Anilist",
            new_name="MalModel",
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="UserModel",
        ),
    ]
