# Generated by Django 4.0.4 on 2022-05-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
        ("anime", "0025_alter_animecharactermodel_options"),
        ("user", "0009_rename_mal_anilistmodel_rename_kitsu_kitsumodel_and_more"),

    ]

    operations = [
        migrations.RenameModel(

            old_name="UserModel",
            new_name="User",

        ),
    ]
