# Generated by Django 4.1a1 on 2022-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial_squashed_0012_alter_anilistmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anilistmodel",
            name="expires_in",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="malmodel",
            name="expires_in",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
