# Generated by Django 4.1a1 on 2022-06-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_anilistmodel_expires_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malmodel",
            name="access_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="malmodel",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
