# Generated by Django 4.2 on 2023-04-14 00:15

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="{uuid:s}{ext}"
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageWithBrightnessAndBackgroundColor",
            fields=[
                (
                    "image_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="images.image",
                    ),
                ),
                ("brightness", models.FloatField()),
                (
                    "background_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
            bases=("images.image", models.Model),
        ),
    ]
