# Generated by Django 4.2 on 2023-04-14 04:03

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagewithbrightnessandbackgroundcolor",
            name="background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="imagewithbrightnessandbackgroundcolor",
            name="brightness",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
