# Generated by Django 4.1.7 on 2023-03-26 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0002_alter_animemodel_rating"),
        ("anime", "0005_alter_animeendingmodel_unique_together_and_more"),
    ]

    operations = []
