# Generated by Django 4.2 on 2023-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0013_animethememodel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animegenremodel",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="animethememodel",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
