# Generated by Django 4.1 on 2022-08-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0002_animeproducermodel_animestudiomodel_charactermodel_and_more"),
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimeProducerModel",
        ),
    ]
