# Generated by Django 4.0 on 2021-12-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avatar", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AvatarCountModel",
        ),
    ]
