# Generated by Django 4.0.3 on 2022-03-11 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0002_alter_capturemodel_options_alter_capturemodel_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaptureModel",
            new_name="CaptureVideoVolumeModel",
        ),
    ]
