# Generated by Django 4.0.3 on 2022-03-11 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0003_rename_capturemodel_capturevideovolumemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturevideovolumemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
