# Generated by Django 4.0.3 on 2022-03-11 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0010_remove_episodemodel_anime_animeinfomodel_episodes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0005_alter_capturevideovolumemodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureAnimeNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.animeinfomodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureEpisodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="upload.episodemodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureVideoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_volume",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "timestamp",
                    models.ManyToManyField(to="capture.captureanimenamemodel"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Video Capture Model",
            },
        ),
        migrations.RemoveField(
            model_name="capturevideovolumemodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="CaptureVideoTimeStampModel",
        ),
        migrations.DeleteModel(
            name="CaptureVideoVolumeModel",
        ),
        migrations.AddField(
            model_name="captureanimenamemodel",
            name="episdoes",
            field=models.ManyToManyField(to="capture.captureepisodemodel"),
        ),
        migrations.AddField(
            model_name="captureanimenamemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
