# Generated by Django 4.0.3 on 2022-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0007_alter_captureanimenamemodel_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureepisodemodel",
            name="timestamp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
