# Generated by Django 4.0.3 on 2022-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0008_alter_captureepisodemodel_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capturevideomodel",
            old_name="timestamp",
            new_name="timestamps",
        ),
    ]
