# Generated by Django 4.0.3 on 2022-03-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0010_remove_episodemodel_anime_animeinfomodel_episodes"),
        ("capture", "0010_rename_episdoes_captureanimenamemodel_episodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureanimenamemodel",
            name="anime",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="upload.animeinfomodel"
            ),
        ),
        migrations.AlterField(
            model_name="captureepisodemodel",
            name="episode",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="upload.episodemodel"
            ),
        ),
    ]
