# Generated by Django 4.0.3 on 2022-03-12 04:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0010_remove_episodemodel_anime_animeinfomodel_episodes"),
        ("capture", "0011_alter_captureanimenamemodel_anime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureanimenamemodel",
            name="anime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="upload.animeinfomodel"
            ),
        ),
        migrations.AlterField(
            model_name="captureepisodemodel",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="upload.episodemodel"
            ),
        ),
        migrations.AlterField(
            model_name="capturevideomodel",
            name="video_volume",
            field=models.PositiveIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
