# Generated by Django 4.0.3 on 2022-03-12 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0011_alter_captureanimenamemodel_anime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturevideomodel",
            name="video_volume",
            field=models.PositiveIntegerField(
                default=50, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
