# Generated by Django 4.0.3 on 2022-03-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0012_alter_captureanimenamemodel_anime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capturevideomodel",
            old_name="timestamps",
            new_name="video_timestamps",
        ),
    ]
