# Generated by Django 4.0.3 on 2022-03-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0013_rename_timestamps_capturevideomodel_video_timestamps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="captureanimenamemodel",
            options={"ordering": ("id",), "verbose_name": "Anime Model"},
        ),
        migrations.AlterModelOptions(
            name="captureepisodemodel",
            options={"ordering": ("id",), "verbose_name": "Episode Model"},
        ),
        migrations.AlterModelOptions(
            name="capturevideomodel",
            options={"ordering": ("user",), "verbose_name": "Main Model"},
        ),
    ]
