# Generated by Django 4.0.3 on 2022-03-12 04:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0014_alter_captureanimenamemodel_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaptureVideoModel",
            new_name="CaptureInfoModel",
        ),
    ]
