# Generated by Django 4.0.3 on 2022-03-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0015_rename_capturevideomodel_captureinfomodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="captureanimenamemodel",
            options={"ordering": ("id",), "verbose_name": "Anime"},
        ),
        migrations.AlterModelOptions(
            name="captureepisodemodel",
            options={"ordering": ("id",), "verbose_name": "Episode"},
        ),
        migrations.AlterModelOptions(
            name="captureinfomodel",
            options={"ordering": ("user",), "verbose_name": "Master"},
        ),
    ]
