# Generated by Django 4.0.3 on 2022-03-12 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0016_alter_captureanimenamemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureinfomodel",
            name="video_volume",
            field=models.PositiveIntegerField(
                default=100, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
