# Generated by Django 4.0.3 on 2022-03-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0018_alter_captureanimenamemodel_anime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureanimenamemodel",
            name="episodes",
            field=models.ManyToManyField(blank=True, to="capture.captureepisodemodel"),
        ),
        migrations.AlterField(
            model_name="captureinfomodel",
            name="video_timestamps",
            field=models.ManyToManyField(
                blank=True, to="capture.captureanimenamemodel"
            ),
        ),
    ]
