# Generated by Django 4.0.3 on 2022-03-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0021_alter_captureinfomodel_video_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureTimeStampModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_timestamps",
                    models.ManyToManyField(
                        blank=True, to="capture.captureanimenamemodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Master",
                "ordering": ("user",),
            },
        ),
        migrations.DeleteModel(
            name="CaptureInfoModel",
        ),
    ]
