# Generated by Django 4.0.3 on 2022-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0022_capturetimestampmodel_delete_captureinfomodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturetimestampmodel",
            name="video_volume",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
