# Generated by Django 4.0.3 on 2022-03-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0023_capturetimestampmodel_video_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capturetimestampmodel",
            name="video_volume",
        ),
    ]
