# Generated by Django 4.0.3 on 2022-03-20 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capture", "0024_remove_capturetimestampmodel_video_volume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capturetimestampmodel",
            options={"ordering": ("user",), "verbose_name": "Master TimeStamps"},
        ),
        migrations.CreateModel(
            name="CaptureVolumeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_volume",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Volumes",
                "ordering": ("user",),
            },
        ),
    ]
