# Generated by Django 4.0.3 on 2022-03-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0025_alter_capturetimestampmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="captureanimenamemodel",
            name="anime",
        ),
    ]
