# Generated by Django 4.0.3 on 2022-03-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0040_animeinfomodel_episodes"),
        ("capture", "0026_remove_captureanimenamemodel_anime"),
    ]

    operations = [
        migrations.AddField(
            model_name="captureanimenamemodel",
            name="anime",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="upload.animeinfomodel",
            ),
            preserve_default=False,
        ),
    ]
