# Generated by Django 4.0.3 on 2022-03-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0027_captureanimenamemodel_anime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="captureepisodemodel",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="captureepisodemodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="capturetimestampmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="capturetimestampmodel",
            name="video_timestamps",
        ),
        migrations.DeleteModel(
            name="CaptureAnimeNameModel",
        ),
        migrations.DeleteModel(
            name="CaptureEpisodeModel",
        ),
        migrations.DeleteModel(
            name="CaptureTimeStampModel",
        ),
    ]
